### ISSUE TITLE
[BUG] update product details

### ISSUE THREAD

**Issue by RakeshSangem** [jaynarayan-vaishnav/hunters-nest#11]
## Changes proposed

- currently pricing card doesn't have unique pricing
- Use props to fix this issue
- Every product much have different prices and description

**Comment by Harsh-garg-coder** [comment]
can you assign this bug to me?

**Comment by RakeshSangem** [comment]
> can you assign this bug to me?
> 

Hey, thanks for showing interest but it is a hackathon project. So we are not accepting any contributions for now. You can check out another repo called `Sharkfolio` we open sourced it.

Thank you, Rakesh:)
